-- Safe Route Phase 1.5 — Supabase setup
-- Run this in Supabase SQL Editor.
-- Then create a Storage bucket named: voice-messages
-- Set the bucket to private for production.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  message_type text not null default 'text' check (message_type in ('text','voice','location')),
  content text,
  media_path text,
  latitude double precision,
  longitude double precision,
  created_at timestamptz not null default now()
);

create table if not exists public.call_signals (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  signal jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.messages enable row level security;
alter table public.call_signals enable row level security;

create policy "profiles_select_authenticated"
on public.profiles for select to authenticated using (true);

create policy "profiles_insert_self"
on public.profiles for insert to authenticated with check (auth.uid() = id);

create policy "messages_select_participants"
on public.messages for select to authenticated
using (auth.uid() = sender_id or auth.uid() = recipient_id);

create policy "messages_insert_sender"
on public.messages for insert to authenticated
with check (auth.uid() = sender_id);

create policy "call_signals_select_participants"
on public.call_signals for select to authenticated
using (auth.uid() = sender_id or auth.uid() = recipient_id);

create policy "call_signals_insert_sender"
on public.call_signals for insert to authenticated
with check (auth.uid() = sender_id);

-- Realtime
alter publication supabase_realtime add table public.messages;
alter publication supabase_realtime add table public.call_signals;

-- Voice storage policies. Bucket must be named voice-messages.
create policy "voice_upload_authenticated"
on storage.objects for insert to authenticated
with check (bucket_id = 'voice-messages');

create policy "voice_read_authenticated"
on storage.objects for select to authenticated
using (bucket_id = 'voice-messages');
